### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Composition
  commentId: N:MarketDataCollector.Application.Composition
  id: MarketDataCollector.Application.Composition
  children:
  - MarketDataCollector.Application.Composition.BackfillHostAdapter
  - MarketDataCollector.Application.Composition.CompositionOptions
  - MarketDataCollector.Application.Composition.ConsoleHostAdapter
  - MarketDataCollector.Application.Composition.DesktopHostAdapter
  - MarketDataCollector.Application.Composition.HostBuilder
  - MarketDataCollector.Application.Composition.HostStartup
  - MarketDataCollector.Application.Composition.HostStartupFactory
  - MarketDataCollector.Application.Composition.IHostAdapter
  - MarketDataCollector.Application.Composition.PipelinePublisher
  - MarketDataCollector.Application.Composition.ServiceCompositionRoot
  - MarketDataCollector.Application.Composition.StreamingHostAdapter
  - MarketDataCollector.Application.Composition.WebHostAdapter
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Composition
  nameWithType: MarketDataCollector.Application.Composition
  fullName: MarketDataCollector.Application.Composition
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Composition.IHostAdapter
  commentId: T:MarketDataCollector.Application.Composition.IHostAdapter
  parent: MarketDataCollector.Application.Composition
  href: MarketDataCollector.Application.Composition.IHostAdapter.html
  name: IHostAdapter
  nameWithType: IHostAdapter
  fullName: MarketDataCollector.Application.Composition.IHostAdapter
- uid: MarketDataCollector.Application.Composition.WebHostAdapter
  commentId: T:MarketDataCollector.Application.Composition.WebHostAdapter
  href: MarketDataCollector.Application.Composition.WebHostAdapter.html
  name: WebHostAdapter
  nameWithType: WebHostAdapter
  fullName: MarketDataCollector.Application.Composition.WebHostAdapter
- uid: MarketDataCollector.Application.Composition.ConsoleHostAdapter
  commentId: T:MarketDataCollector.Application.Composition.ConsoleHostAdapter
  href: MarketDataCollector.Application.Composition.ConsoleHostAdapter.html
  name: ConsoleHostAdapter
  nameWithType: ConsoleHostAdapter
  fullName: MarketDataCollector.Application.Composition.ConsoleHostAdapter
- uid: MarketDataCollector.Application.Composition.DesktopHostAdapter
  commentId: T:MarketDataCollector.Application.Composition.DesktopHostAdapter
  href: MarketDataCollector.Application.Composition.DesktopHostAdapter.html
  name: DesktopHostAdapter
  nameWithType: DesktopHostAdapter
  fullName: MarketDataCollector.Application.Composition.DesktopHostAdapter
- uid: MarketDataCollector.Application.Composition.StreamingHostAdapter
  commentId: T:MarketDataCollector.Application.Composition.StreamingHostAdapter
  href: MarketDataCollector.Application.Composition.StreamingHostAdapter.html
  name: StreamingHostAdapter
  nameWithType: StreamingHostAdapter
  fullName: MarketDataCollector.Application.Composition.StreamingHostAdapter
- uid: MarketDataCollector.Application.Composition.BackfillHostAdapter
  commentId: T:MarketDataCollector.Application.Composition.BackfillHostAdapter
  href: MarketDataCollector.Application.Composition.BackfillHostAdapter.html
  name: BackfillHostAdapter
  nameWithType: BackfillHostAdapter
  fullName: MarketDataCollector.Application.Composition.BackfillHostAdapter
- uid: MarketDataCollector.Application.Composition.HostBuilder
  commentId: T:MarketDataCollector.Application.Composition.HostBuilder
  parent: MarketDataCollector.Application.Composition
  href: MarketDataCollector.Application.Composition.HostBuilder.html
  name: HostBuilder
  nameWithType: HostBuilder
  fullName: MarketDataCollector.Application.Composition.HostBuilder
- uid: MarketDataCollector.Application.Composition.HostStartup
  commentId: T:MarketDataCollector.Application.Composition.HostStartup
  parent: MarketDataCollector.Application.Composition
  href: MarketDataCollector.Application.Composition.HostStartup.html
  name: HostStartup
  nameWithType: HostStartup
  fullName: MarketDataCollector.Application.Composition.HostStartup
- uid: MarketDataCollector.Application.Composition.HostStartupFactory
  commentId: T:MarketDataCollector.Application.Composition.HostStartupFactory
  href: MarketDataCollector.Application.Composition.HostStartupFactory.html
  name: HostStartupFactory
  nameWithType: HostStartupFactory
  fullName: MarketDataCollector.Application.Composition.HostStartupFactory
- uid: MarketDataCollector.Application.Composition.ServiceCompositionRoot
  commentId: T:MarketDataCollector.Application.Composition.ServiceCompositionRoot
  href: MarketDataCollector.Application.Composition.ServiceCompositionRoot.html
  name: ServiceCompositionRoot
  nameWithType: ServiceCompositionRoot
  fullName: MarketDataCollector.Application.Composition.ServiceCompositionRoot
- uid: MarketDataCollector.Application.Composition.PipelinePublisher
  commentId: T:MarketDataCollector.Application.Composition.PipelinePublisher
  href: MarketDataCollector.Application.Composition.PipelinePublisher.html
  name: PipelinePublisher
  nameWithType: PipelinePublisher
  fullName: MarketDataCollector.Application.Composition.PipelinePublisher
- uid: MarketDataCollector.Application.Composition.CompositionOptions
  commentId: T:MarketDataCollector.Application.Composition.CompositionOptions
  parent: MarketDataCollector.Application.Composition
  href: MarketDataCollector.Application.Composition.CompositionOptions.html
  name: CompositionOptions
  nameWithType: CompositionOptions
  fullName: MarketDataCollector.Application.Composition.CompositionOptions
- uid: MarketDataCollector.Application.Composition
  commentId: N:MarketDataCollector.Application.Composition
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Composition
  nameWithType: MarketDataCollector.Application.Composition
  fullName: MarketDataCollector.Application.Composition
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Composition
    name: Composition
    href: MarketDataCollector.Application.Composition.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Composition
    name: Composition
    href: MarketDataCollector.Application.Composition.html
