### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Logging
  commentId: N:MarketDataCollector.Application.Logging
  id: MarketDataCollector.Application.Logging
  children:
  - MarketDataCollector.Application.Logging.LoggingSetup
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Logging
  nameWithType: MarketDataCollector.Application.Logging
  fullName: MarketDataCollector.Application.Logging
  type: Namespace
  assemblies:
  - MarketDataCollector.Core
references:
- uid: MarketDataCollector.Application.Logging.LoggingSetup
  commentId: T:MarketDataCollector.Application.Logging.LoggingSetup
  href: MarketDataCollector.Application.Logging.LoggingSetup.html
  name: LoggingSetup
  nameWithType: LoggingSetup
  fullName: MarketDataCollector.Application.Logging.LoggingSetup
