### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Tracing
  commentId: N:MarketDataCollector.Application.Tracing
  id: MarketDataCollector.Application.Tracing
  children:
  - MarketDataCollector.Application.Tracing.MarketDataTracing
  - MarketDataCollector.Application.Tracing.OpenTelemetryConfiguration
  - MarketDataCollector.Application.Tracing.OpenTelemetrySetup
  - MarketDataCollector.Application.Tracing.TracedEventMetrics
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Tracing
  nameWithType: MarketDataCollector.Application.Tracing
  fullName: MarketDataCollector.Application.Tracing
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Tracing.OpenTelemetrySetup
  commentId: T:MarketDataCollector.Application.Tracing.OpenTelemetrySetup
  href: MarketDataCollector.Application.Tracing.OpenTelemetrySetup.html
  name: OpenTelemetrySetup
  nameWithType: OpenTelemetrySetup
  fullName: MarketDataCollector.Application.Tracing.OpenTelemetrySetup
- uid: MarketDataCollector.Application.Tracing.MarketDataTracing
  commentId: T:MarketDataCollector.Application.Tracing.MarketDataTracing
  href: MarketDataCollector.Application.Tracing.MarketDataTracing.html
  name: MarketDataTracing
  nameWithType: MarketDataTracing
  fullName: MarketDataCollector.Application.Tracing.MarketDataTracing
- uid: MarketDataCollector.Application.Tracing.OpenTelemetryConfiguration
  commentId: T:MarketDataCollector.Application.Tracing.OpenTelemetryConfiguration
  parent: MarketDataCollector.Application.Tracing
  href: MarketDataCollector.Application.Tracing.OpenTelemetryConfiguration.html
  name: OpenTelemetryConfiguration
  nameWithType: OpenTelemetryConfiguration
  fullName: MarketDataCollector.Application.Tracing.OpenTelemetryConfiguration
- uid: MarketDataCollector.Application.Tracing.TracedEventMetrics
  commentId: T:MarketDataCollector.Application.Tracing.TracedEventMetrics
  href: MarketDataCollector.Application.Tracing.TracedEventMetrics.html
  name: TracedEventMetrics
  nameWithType: TracedEventMetrics
  fullName: MarketDataCollector.Application.Tracing.TracedEventMetrics
- uid: MarketDataCollector.Application.Tracing
  commentId: N:MarketDataCollector.Application.Tracing
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Tracing
  nameWithType: MarketDataCollector.Application.Tracing
  fullName: MarketDataCollector.Application.Tracing
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Tracing
    name: Tracing
    href: MarketDataCollector.Application.Tracing.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Tracing
    name: Tracing
    href: MarketDataCollector.Application.Tracing.html
