### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.ResultTypes
  commentId: N:MarketDataCollector.Application.ResultTypes
  id: MarketDataCollector.Application.ResultTypes
  children:
  - MarketDataCollector.Application.ResultTypes.ErrorCode
  - MarketDataCollector.Application.ResultTypes.ErrorCodeExtensions
  - MarketDataCollector.Application.ResultTypes.OperationError
  - MarketDataCollector.Application.ResultTypes.Result
  - MarketDataCollector.Application.ResultTypes.Result`1
  - MarketDataCollector.Application.ResultTypes.Result`2
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.ResultTypes
  nameWithType: MarketDataCollector.Application.ResultTypes
  fullName: MarketDataCollector.Application.ResultTypes
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.ResultTypes.ErrorCode
  commentId: T:MarketDataCollector.Application.ResultTypes.ErrorCode
  parent: MarketDataCollector.Application.ResultTypes
  href: MarketDataCollector.Application.ResultTypes.ErrorCode.html
  name: ErrorCode
  nameWithType: ErrorCode
  fullName: MarketDataCollector.Application.ResultTypes.ErrorCode
- uid: MarketDataCollector.Application.ResultTypes.ErrorCodeExtensions
  commentId: T:MarketDataCollector.Application.ResultTypes.ErrorCodeExtensions
  parent: MarketDataCollector.Application.ResultTypes
  href: MarketDataCollector.Application.ResultTypes.ErrorCodeExtensions.html
  name: ErrorCodeExtensions
  nameWithType: ErrorCodeExtensions
  fullName: MarketDataCollector.Application.ResultTypes.ErrorCodeExtensions
- uid: MarketDataCollector.Application.ResultTypes.OperationError
  commentId: T:MarketDataCollector.Application.ResultTypes.OperationError
  parent: MarketDataCollector.Application.ResultTypes
  href: MarketDataCollector.Application.ResultTypes.OperationError.html
  name: OperationError
  nameWithType: OperationError
  fullName: MarketDataCollector.Application.ResultTypes.OperationError
- uid: MarketDataCollector.Application.ResultTypes.Result`2
  commentId: T:MarketDataCollector.Application.ResultTypes.Result`2
  parent: MarketDataCollector.Application.ResultTypes
  href: MarketDataCollector.Application.ResultTypes.Result-2.html
  name: Result<TValue, TError>
  nameWithType: Result<TValue, TError>
  fullName: MarketDataCollector.Application.ResultTypes.Result<TValue, TError>
  nameWithType.vb: Result(Of TValue, TError)
  fullName.vb: MarketDataCollector.Application.ResultTypes.Result(Of TValue, TError)
  name.vb: Result(Of TValue, TError)
  spec.csharp:
  - uid: MarketDataCollector.Application.ResultTypes.Result`2
    name: Result
    href: MarketDataCollector.Application.ResultTypes.Result-2.html
  - name: <
  - name: TValue
  - name: ','
  - name: " "
  - name: TError
  - name: '>'
  spec.vb:
  - uid: MarketDataCollector.Application.ResultTypes.Result`2
    name: Result
    href: MarketDataCollector.Application.ResultTypes.Result-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: ','
  - name: " "
  - name: TError
  - name: )
- uid: MarketDataCollector.Application.ResultTypes.Result`1
  commentId: T:MarketDataCollector.Application.ResultTypes.Result`1
  parent: MarketDataCollector.Application.ResultTypes
  href: MarketDataCollector.Application.ResultTypes.Result-1.html
  name: Result<TError>
  nameWithType: Result<TError>
  fullName: MarketDataCollector.Application.ResultTypes.Result<TError>
  nameWithType.vb: Result(Of TError)
  fullName.vb: MarketDataCollector.Application.ResultTypes.Result(Of TError)
  name.vb: Result(Of TError)
  spec.csharp:
  - uid: MarketDataCollector.Application.ResultTypes.Result`1
    name: Result
    href: MarketDataCollector.Application.ResultTypes.Result-1.html
  - name: <
  - name: TError
  - name: '>'
  spec.vb:
  - uid: MarketDataCollector.Application.ResultTypes.Result`1
    name: Result
    href: MarketDataCollector.Application.ResultTypes.Result-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TError
  - name: )
- uid: MarketDataCollector.Application.ResultTypes.Result
  commentId: T:MarketDataCollector.Application.ResultTypes.Result
  href: MarketDataCollector.Application.ResultTypes.Result.html
  name: Result
  nameWithType: Result
  fullName: MarketDataCollector.Application.ResultTypes.Result
- uid: MarketDataCollector.Application.ResultTypes
  commentId: N:MarketDataCollector.Application.ResultTypes
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.ResultTypes
  nameWithType: MarketDataCollector.Application.ResultTypes
  fullName: MarketDataCollector.Application.ResultTypes
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.ResultTypes
    name: ResultTypes
    href: MarketDataCollector.Application.ResultTypes.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.ResultTypes
    name: ResultTypes
    href: MarketDataCollector.Application.ResultTypes.html
