### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Commands
  commentId: N:MarketDataCollector.Application.Commands
  id: MarketDataCollector.Application.Commands
  children:
  - MarketDataCollector.Application.Commands.CliResult
  - MarketDataCollector.Application.Commands.ICliCommand
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Commands
  nameWithType: MarketDataCollector.Application.Commands
  fullName: MarketDataCollector.Application.Commands
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Commands.ICliCommand
  commentId: T:MarketDataCollector.Application.Commands.ICliCommand
  href: MarketDataCollector.Application.Commands.ICliCommand.html
  name: ICliCommand
  nameWithType: ICliCommand
  fullName: MarketDataCollector.Application.Commands.ICliCommand
- uid: MarketDataCollector.Application.Commands.CliResult
  commentId: T:MarketDataCollector.Application.Commands.CliResult
  parent: MarketDataCollector.Application.Commands
  href: MarketDataCollector.Application.Commands.CliResult.html
  name: CliResult
  nameWithType: CliResult
  fullName: MarketDataCollector.Application.Commands.CliResult
- uid: MarketDataCollector.Application.Commands
  commentId: N:MarketDataCollector.Application.Commands
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Commands
  nameWithType: MarketDataCollector.Application.Commands
  fullName: MarketDataCollector.Application.Commands
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Commands
    name: Commands
    href: MarketDataCollector.Application.Commands.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Commands
    name: Commands
    href: MarketDataCollector.Application.Commands.html
