### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Subscriptions
  commentId: N:MarketDataCollector.Application.Subscriptions
  id: MarketDataCollector.Application.Subscriptions
  children:
  - MarketDataCollector.Application.Subscriptions.SubscriptionOrchestrator
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Subscriptions
  nameWithType: MarketDataCollector.Application.Subscriptions
  fullName: MarketDataCollector.Application.Subscriptions
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Subscriptions.SubscriptionOrchestrator
  commentId: T:MarketDataCollector.Application.Subscriptions.SubscriptionOrchestrator
  parent: MarketDataCollector.Application.Subscriptions
  href: MarketDataCollector.Application.Subscriptions.SubscriptionOrchestrator.html
  name: SubscriptionOrchestrator
  nameWithType: SubscriptionOrchestrator
  fullName: MarketDataCollector.Application.Subscriptions.SubscriptionOrchestrator
- uid: MarketDataCollector.Application.Subscriptions
  commentId: N:MarketDataCollector.Application.Subscriptions
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Subscriptions
  nameWithType: MarketDataCollector.Application.Subscriptions
  fullName: MarketDataCollector.Application.Subscriptions
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Subscriptions
    name: Subscriptions
    href: MarketDataCollector.Application.Subscriptions.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Subscriptions
    name: Subscriptions
    href: MarketDataCollector.Application.Subscriptions.html
