### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Serialization
  commentId: N:MarketDataCollector.Application.Serialization
  id: MarketDataCollector.Application.Serialization
  children:
  - MarketDataCollector.Application.Serialization.AlpacaJsonContext
  - MarketDataCollector.Application.Serialization.AlpacaMessage
  - MarketDataCollector.Application.Serialization.AlpacaQuoteMessage
  - MarketDataCollector.Application.Serialization.AlpacaTradeMessage
  - MarketDataCollector.Application.Serialization.HighPerformanceJson
  - MarketDataCollector.Application.Serialization.JsonBenchmarkUtilities
  - MarketDataCollector.Application.Serialization.MarketDataJsonContext
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Serialization
  nameWithType: MarketDataCollector.Application.Serialization
  fullName: MarketDataCollector.Application.Serialization
  type: Namespace
  assemblies:
  - MarketDataCollector.Core
references:
- uid: MarketDataCollector.Application.Serialization.MarketDataJsonContext
  commentId: T:MarketDataCollector.Application.Serialization.MarketDataJsonContext
  parent: MarketDataCollector.Application.Serialization
  href: MarketDataCollector.Application.Serialization.MarketDataJsonContext.html
  name: MarketDataJsonContext
  nameWithType: MarketDataJsonContext
  fullName: MarketDataCollector.Application.Serialization.MarketDataJsonContext
- uid: MarketDataCollector.Application.Serialization.AlpacaJsonContext
  commentId: T:MarketDataCollector.Application.Serialization.AlpacaJsonContext
  parent: MarketDataCollector.Application.Serialization
  href: MarketDataCollector.Application.Serialization.AlpacaJsonContext.html
  name: AlpacaJsonContext
  nameWithType: AlpacaJsonContext
  fullName: MarketDataCollector.Application.Serialization.AlpacaJsonContext
- uid: MarketDataCollector.Application.Serialization.AlpacaTradeMessage
  commentId: T:MarketDataCollector.Application.Serialization.AlpacaTradeMessage
  parent: MarketDataCollector.Application.Serialization
  href: MarketDataCollector.Application.Serialization.AlpacaTradeMessage.html
  name: AlpacaTradeMessage
  nameWithType: AlpacaTradeMessage
  fullName: MarketDataCollector.Application.Serialization.AlpacaTradeMessage
- uid: MarketDataCollector.Application.Serialization.AlpacaQuoteMessage
  commentId: T:MarketDataCollector.Application.Serialization.AlpacaQuoteMessage
  parent: MarketDataCollector.Application.Serialization
  href: MarketDataCollector.Application.Serialization.AlpacaQuoteMessage.html
  name: AlpacaQuoteMessage
  nameWithType: AlpacaQuoteMessage
  fullName: MarketDataCollector.Application.Serialization.AlpacaQuoteMessage
- uid: MarketDataCollector.Application.Serialization.AlpacaMessage
  commentId: T:MarketDataCollector.Application.Serialization.AlpacaMessage
  href: MarketDataCollector.Application.Serialization.AlpacaMessage.html
  name: AlpacaMessage
  nameWithType: AlpacaMessage
  fullName: MarketDataCollector.Application.Serialization.AlpacaMessage
- uid: MarketDataCollector.Application.Serialization.HighPerformanceJson
  commentId: T:MarketDataCollector.Application.Serialization.HighPerformanceJson
  href: MarketDataCollector.Application.Serialization.HighPerformanceJson.html
  name: HighPerformanceJson
  nameWithType: HighPerformanceJson
  fullName: MarketDataCollector.Application.Serialization.HighPerformanceJson
- uid: MarketDataCollector.Application.Serialization.JsonBenchmarkUtilities
  commentId: T:MarketDataCollector.Application.Serialization.JsonBenchmarkUtilities
  href: MarketDataCollector.Application.Serialization.JsonBenchmarkUtilities.html
  name: JsonBenchmarkUtilities
  nameWithType: JsonBenchmarkUtilities
  fullName: MarketDataCollector.Application.Serialization.JsonBenchmarkUtilities
- uid: MarketDataCollector.Application.Serialization
  commentId: N:MarketDataCollector.Application.Serialization
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Serialization
  nameWithType: MarketDataCollector.Application.Serialization
  fullName: MarketDataCollector.Application.Serialization
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Serialization
    name: Serialization
    href: MarketDataCollector.Application.Serialization.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Serialization
    name: Serialization
    href: MarketDataCollector.Application.Serialization.html
