### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Filters
  commentId: N:MarketDataCollector.Application.Filters
  id: MarketDataCollector.Application.Filters
  children:
  - MarketDataCollector.Application.Filters.MarketEventFilter
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Filters
  nameWithType: MarketDataCollector.Application.Filters
  fullName: MarketDataCollector.Application.Filters
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Filters.MarketEventFilter
  commentId: T:MarketDataCollector.Application.Filters.MarketEventFilter
  parent: MarketDataCollector.Application.Filters
  href: MarketDataCollector.Application.Filters.MarketEventFilter.html
  name: MarketEventFilter
  nameWithType: MarketEventFilter
  fullName: MarketDataCollector.Application.Filters.MarketEventFilter
- uid: MarketDataCollector.Application.Filters
  commentId: N:MarketDataCollector.Application.Filters
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Filters
  nameWithType: MarketDataCollector.Application.Filters
  fullName: MarketDataCollector.Application.Filters
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Filters
    name: Filters
    href: MarketDataCollector.Application.Filters.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Filters
    name: Filters
    href: MarketDataCollector.Application.Filters.html
