### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Credentials
  commentId: N:MarketDataCollector.Application.Credentials
  id: MarketDataCollector.Application.Credentials
  children:
  - MarketDataCollector.Application.Credentials.CredentialMetadata
  - MarketDataCollector.Application.Credentials.CredentialResult
  - MarketDataCollector.Application.Credentials.CredentialSource
  - MarketDataCollector.Application.Credentials.CredentialStoreExtensions
  - MarketDataCollector.Application.Credentials.CredentialType
  - MarketDataCollector.Application.Credentials.CredentialValidationResult
  - MarketDataCollector.Application.Credentials.ICredentialStore
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Credentials
  nameWithType: MarketDataCollector.Application.Credentials
  fullName: MarketDataCollector.Application.Credentials
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Credentials.CredentialType
  commentId: T:MarketDataCollector.Application.Credentials.CredentialType
  parent: MarketDataCollector.Application.Credentials
  href: MarketDataCollector.Application.Credentials.CredentialType.html
  name: CredentialType
  nameWithType: CredentialType
  fullName: MarketDataCollector.Application.Credentials.CredentialType
- uid: MarketDataCollector.Application.Credentials.CredentialMetadata
  commentId: T:MarketDataCollector.Application.Credentials.CredentialMetadata
  parent: MarketDataCollector.Application.Credentials
  href: MarketDataCollector.Application.Credentials.CredentialMetadata.html
  name: CredentialMetadata
  nameWithType: CredentialMetadata
  fullName: MarketDataCollector.Application.Credentials.CredentialMetadata
- uid: MarketDataCollector.Application.Credentials.CredentialResult
  commentId: T:MarketDataCollector.Application.Credentials.CredentialResult
  parent: MarketDataCollector.Application.Credentials
  href: MarketDataCollector.Application.Credentials.CredentialResult.html
  name: CredentialResult
  nameWithType: CredentialResult
  fullName: MarketDataCollector.Application.Credentials.CredentialResult
- uid: MarketDataCollector.Application.Credentials.CredentialSource
  commentId: T:MarketDataCollector.Application.Credentials.CredentialSource
  parent: MarketDataCollector.Application.Credentials
  href: MarketDataCollector.Application.Credentials.CredentialSource.html
  name: CredentialSource
  nameWithType: CredentialSource
  fullName: MarketDataCollector.Application.Credentials.CredentialSource
- uid: MarketDataCollector.Application.Credentials.ICredentialStore
  commentId: T:MarketDataCollector.Application.Credentials.ICredentialStore
  parent: MarketDataCollector.Application.Credentials
  href: MarketDataCollector.Application.Credentials.ICredentialStore.html
  name: ICredentialStore
  nameWithType: ICredentialStore
  fullName: MarketDataCollector.Application.Credentials.ICredentialStore
- uid: MarketDataCollector.Application.Credentials.CredentialValidationResult
  commentId: T:MarketDataCollector.Application.Credentials.CredentialValidationResult
  href: MarketDataCollector.Application.Credentials.CredentialValidationResult.html
  name: CredentialValidationResult
  nameWithType: CredentialValidationResult
  fullName: MarketDataCollector.Application.Credentials.CredentialValidationResult
- uid: MarketDataCollector.Application.Credentials.CredentialStoreExtensions
  commentId: T:MarketDataCollector.Application.Credentials.CredentialStoreExtensions
  parent: MarketDataCollector.Application.Credentials
  href: MarketDataCollector.Application.Credentials.CredentialStoreExtensions.html
  name: CredentialStoreExtensions
  nameWithType: CredentialStoreExtensions
  fullName: MarketDataCollector.Application.Credentials.CredentialStoreExtensions
- uid: MarketDataCollector.Application.Credentials
  commentId: N:MarketDataCollector.Application.Credentials
  href: MarketDataCollector.html
  name: MarketDataCollector.Application.Credentials
  nameWithType: MarketDataCollector.Application.Credentials
  fullName: MarketDataCollector.Application.Credentials
  spec.csharp:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Credentials
    name: Credentials
    href: MarketDataCollector.Application.Credentials.html
  spec.vb:
  - uid: MarketDataCollector
    name: MarketDataCollector
    href: MarketDataCollector.html
  - name: .
  - uid: MarketDataCollector.Application
    name: Application
    href: MarketDataCollector.Application.html
  - name: .
  - uid: MarketDataCollector.Application.Credentials
    name: Credentials
    href: MarketDataCollector.Application.Credentials.html
