### YamlMime:ManagedReference
items:
- uid: MarketDataCollector.Application.Testing
  commentId: N:MarketDataCollector.Application.Testing
  id: MarketDataCollector.Application.Testing
  children:
  - MarketDataCollector.Application.Testing.DepthBufferSelfTests
  langs:
  - csharp
  - vb
  name: MarketDataCollector.Application.Testing
  nameWithType: MarketDataCollector.Application.Testing
  fullName: MarketDataCollector.Application.Testing
  type: Namespace
  assemblies:
  - MarketDataCollector.Application
references:
- uid: MarketDataCollector.Application.Testing.DepthBufferSelfTests
  commentId: T:MarketDataCollector.Application.Testing.DepthBufferSelfTests
  href: MarketDataCollector.Application.Testing.DepthBufferSelfTests.html
  name: DepthBufferSelfTests
  nameWithType: DepthBufferSelfTests
  fullName: MarketDataCollector.Application.Testing.DepthBufferSelfTests
